ARG RUBY_VERSION

FROM ruby:${RUBY_VERSION}-slim
RUN apt-get update -qq && apt-get install -y  build-essential libpq-dev nodejs nano curl

# Add Yarn repository
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Update
RUN apt-get update -y

# Install Yarn
RUN apt-get install -y yarn

WORKDIR /app
