name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image rails260
        run: |
          docker buildx build --push \
            -f Dockerfile_rails --build-arg RUBY_VERSION=2.6.0 \
            --tag otrodeteruel/rails260:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
      - name: build the image
        run: |
          docker buildx build --push \
            -f Dockerfile_nginx --build-arg NGINX_VERSION=1.17.3 \
            --tag otrodeteruel/ngnix1173:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .

